name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

jobs:
  avoid_reduncy:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '16'
      - name: npm install
        run: npm ci
      - name: build js
        run : npx ncc build index.ts
      - name: create zip
        run : zip -j deploy.zip ./dist/*
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./deploy.zip

  test:
    needs: build
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-18.04
    steps:
      - name: Running test
        run: echo "Ruuuuuning test!!!"

  deploy_lambda:
    needs: build
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-18.04
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: ./
      - name: deploy
        run: aws lambda update-function-code --function-name=lambda-gh-init --zip-file=fileb://deploy.zip